### ISSUE TITLE
模型调优

### ISSUE THREAD

**Issue by Northxw** [nladuo/captcha-break#11]
(Ps: 如果K的取值是调优过后选择的，请忽略该条issue)
您好，识别脚本中KNN应加入网格搜索GridSearchCV，K的取值让模型判断，CV就按10折来搞吧。

**Comment by nladuo** [comment]
这个没必要加，一共只有60个数据，每个数据6条，然后数据都是区分度比较大的。k取1，3，5，7其实都一样。
