### ISSUE TITLE
Ubuntu16.04   os.mkdir(save_path) OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by HaoYangMa** [nladuo/captcha-break#7]
generating: ./dataset/啊
Traceback (most recent call last):
  File "/home/hya/PycharmProjects/resource/captcha-break/weibo.cn2/generate_dataset/main.py", line 45, in <module>
    os.mkdir(save_path)
OSError: [Errno 2] No such file or directory: './dataset/\xe5\x95\x8a'

    for i, ch in enumerate(chars):
        if i > 20:
            break
        save_path = "./dataset/" + str(ch)
        print "generating:", save_path
        if not os.path.exists(save_path):
            os.mkdir(save_path)      #这里报错
        # generate 360 sample for every character
        for i in range(-30, 30, 1):
            for j in range(6):
                generate_data(ch, i, save_path)

**Comment by nladuo** [comment]
这个还在开发中，还没有整理好，目前无法使用。
